# -*- coding: utf-8 -*-
"""Tugas ulangan tengah semester.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u0TPUI6hMfXKiZrsj0j-fjr_ZsCrFPLy
"""

def faktorial(n):
    if n == 0 or n == 1:
        return 1
    else:
        return n * faktorial(n - 1)

angka = int(input("Masukkan angka: "))
print(f"Faktorial dari {angka} adalah {faktorial(angka)}")

nilai_siswa = []

for i in range(5):
    nilai = float(input(f"Masukkan nilai siswa ke-{i+1}: "))
    nilai_siswa.append(nilai)

nilai_tertinggi = max(nilai_siswa)
siswa_ke = nilai_siswa.index(nilai_tertinggi) + 1

print(f"Nilai tertinggi adalah {nilai_tertinggi}, didapat oleh siswa ke-{siswa_ke}")

total_belanja = float(input("Masukkan total belanja (Rp): "))

if total_belanja > 500000:
    total_bayar = total_belanja * 0.9
    print("Anda mendapatkan diskon 10%")
else:
    total_bayar = total_belanja

print(f"Total yang harus dibayar: Rp{total_bayar}")

# Input total belanja dengan validasi
while True:
    try:
        total_belanja = float(input("Total belanja: Rp"))
        if total_belanja >= 0:
            break
        else:
            print("Total tidak boleh negatif!")
    except ValueError:
        print("Masukkan angka yang valid!")

# Logika diskon
if total_belanja > 500000:
    diskon = total_belanja * 0.1
    total_bayar = total_belanja - diskon
    print(f"\nSelamat! Anda dapat diskon 10%")
    print(f"Diskon: Rp{diskon:,.2f}")
else:
    total_bayar = total_belanja
    print("\nBelanja kembali untuk dapat diskon 10%!")

# Format output dengan separator ribuan
print(f"Total belanja: Rp{total_belanja:,.2f}")
print(f"Total bayar: Rp{total_bayar:,.2f}")

print("Program Penentu Kelulusan")

nilai1 = float(input("Masukkan nilai mata pelajaran 1: "))
nilai2 = float(input("Masukkan nilai mata pelajaran 2: "))
nilai3 = float(input("Masukkan nilai mata pelajaran 3: "))

rata_rata = (nilai1 + nilai2 + nilai3) / 3

print(f"Rata-rata nilai: {rata_rata}")

if rata_rata >= 75:
    print("Status: LULUS")
else:
    print("Status: TIDAK LULUS")